import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header/Header'
import { useAuthContext } from '@/context/AuthContext'
import InputBox from '@/components/InputBox'
import Posts from '@/components/Posts/Posts'
import { neueWorld, pierSans } from '@/fonts/fonts'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { user } = useAuthContext()

  return (
    <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {user !== undefined && user !== null ? (
          <>
            <Header />
            <InputBox />
            <Posts />
          </>
        ) : (
          <div className="w-full h-full flex justify-center items-center">
            <h2>Welcome to the Creative Network, please log in</h2>
            <button>sign in</button>
          </div>
        )}
    </>
  )
}
