import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import { useAuthContext } from '@/context/AuthContext'
import InputBox from '@/components/InputBox'
import Posts from '@/components/Posts'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { user } = useAuthContext()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {user !== undefined && user !== null ? (
        <>
          <Header />
          <InputBox />
          <Posts />
        </>
      ) : (
        <p>
          please <button>sign in</button>
        </p>
      )}
    </>
  )
}
